spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/carrotdiary
    username: sa
    password:
    driver-class-name: org.h2.Driver

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        accessKey: AKIA4IW5FFSSCRDRFCGV
        secretKey: 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
      s3:
        bucketName: carrotdiary-s3bucket
      region:
        static: ap-northeast-2
      stack:
        auto: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


